=== glynch/jscene3d/jscene3d-project/src/main/resources/META-INF/jscene3d/project/resource-1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://jscene3d.org/schemas/resource-1.json",
  "title": "JScene3D Resource version 1",
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "type", "typeVersion"],
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri-reference"
    },
    "schemaVersion": {
      "const": 1
    },
    "type": {
      "type": "string"
    },
    "typeVersion": {
      "type": "integer",
      "minimum": 1
    },
    "properties": {
      "type": "object"
    }
  }
}

=== glynch/jscene3d/jscene3d-project-examples/src/main/editor-sandbox/resources/cube.material.resource.json
{
  "$schema" : "https://jscene3d.org/schemas/resource-1.json",
  "schemaVersion" : 1,
  "type" : "io.github.glynch.jscene3d.spatial3d/standard-material-resource",
  "typeVersion" : 1,
  "properties" : {
    "color" : [ 0.043735027, 0.22322798, 0.92158204 ],
    "metalness" : 0.0,
    "roughness" : 0.35,
    "emissive" : [ 0.0, 0.0, 0.0 ],
    "emissive-intensity" : 1.0,
    "opacity" : 1.0,
    "alpha-mode" : "opaque",
    "alpha-cutoff" : 0.5,
    "side" : "front",
    "vertex-colors" : false
  }
}

=== glynch/jscene3d/jscene3d-project-examples/src/main/project/resources/cube.shape.json
{
  "schemaVersion": 1,
  "type": "io.github.glynch.jscene3d/triangle-mesh-shape-3d",
  "typeVersion": 1,
  "properties": {
    "positions": [
      -1, -1, -1,
      1, -1, -1,
      1, 1, -1,
      -1, 1, -1,
      -1, -1, 1,
      1, -1, 1,
      1, 1, 1,
      -1, 1, 1
    ],
    "indices": [
      0, 2, 1, 0, 3, 2,
      4, 5, 6, 4, 6, 7,
      0, 1, 5, 0, 5, 4,
      3, 7, 6, 3, 6, 2,
      0, 4, 7, 0, 7, 3,
      1, 2, 6, 1, 6, 5
    ]
  }
}
